# Generated by Django 6.0.3 on 2026-03-07 13:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_legacy_integration'),
        ('shipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='shipment',
            name='shipments_s_order_i_38988b_idx',
        ),
        migrations.RemoveIndex(
            model_name='shipment',
            name='shipments_s_owner_i_31fe54_idx',
        ),
        migrations.AddField(
            model_name='shipment',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shipments_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination',
            field=models.ForeignKey(default=1, help_text='Warehouse where shipment is delivered', on_delete=django.db.models.deletion.PROTECT, related_name='shipments_to', to='products.warehouse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the shipment'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin',
            field=models.ForeignKey(default=1, help_text='Warehouse where shipment originates', on_delete=django.db.models.deletion.PROTECT, related_name='shipments_from', to='products.warehouse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('IN_TRANSIT', 'In Transit'), ('AT_PORT', 'At Port'), ('CUSTOMS_CLEARANCE', 'Customs Clearance'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('RECEIVED', 'Received')], default='CREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['origin', '-created_at'], name='shipments_s_origin__7622a4_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['destination', '-created_at'], name='shipments_s_destina_2898e2_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['created_by', '-created_at'], name='shipments_s_created_9abe02_idx'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='products.product'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipments.shipment'),
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='recipient_email',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='recipient_name',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='shipping_city',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='shipping_country',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='shipping_state',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='shipping_zip',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='warehouse',
        ),
        migrations.AddIndex(
            model_name='shipmentitem',
            index=models.Index(fields=['shipment', 'product'], name='shipments_s_shipmen_78a360_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shipmentitem',
            unique_together={('shipment', 'product')},
        ),
    ]
