$kind: http-request
name: List Inventory
method: GET
url: '{{base_url}}/api/inventory/'
order: 1000
queryParams:
  - key: page
    value: '1'
    disabled: true
  - key: warehouse
    value: ''
    disabled: true
  - key: product
    value: ''
    disabled: true
  - key: low_stock
    value: 'true'
    disabled: true
