# Generated by Django 6.0.3 on 2026-03-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_role_add_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_approve_requests',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_dispatch_requests',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
