# Generated by Django 6.0.3 on 2026-03-10 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_shopifywebhookdelivery'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='shopifywebhookdelivery',
            new_name='integration_topic_1f4b60_idx',
            old_name='integration_topic_7b91ce_idx',
        ),
        migrations.RenameIndex(
            model_name='shopifywebhookdelivery',
            new_name='integration_status_91b54d_idx',
            old_name='integration_status_556497_idx',
        ),
    ]
