# Generated by Django 6.0.3 on 2026-03-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_odoocredentials_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifycredentials',
            name='api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='shopifycredentials',
            name='api_secret',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]

