# Generated by Django 6.0.3 on 2026-03-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_shopifycredentials_api_key_and_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='odoocredentials',
            name='ecommerce_partner_id',
            field=models.CharField(blank=True, default='', help_text='Odoo partner ID for regular e-commerce orders', max_length=255),
        ),
        migrations.AddField(
            model_name='odoocredentials',
            name='pos_partner_id',
            field=models.CharField(blank=True, default='', help_text='Odoo partner ID for POS orders', max_length=255),
        ),
        migrations.AddField(
            model_name='odoocredentials',
            name='sukhiba_partner_id',
            field=models.CharField(blank=True, default='', help_text='Odoo partner ID for orders tagged origin:sukhiba', max_length=255),
        ),
    ]
