# Generated by Django 6.0.3 on 2026-03-17 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_add_quickbooks_customer_ids'),
        ('orders', '0010_order_odoo_sync_status_order_quickbooks_sync_status'),
        ('products', '0010_add_quickbooks_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='auto_sync_orders',
            field=models.BooleanField(default=False, help_text='Automatically push new orders to this platform when they arrive.'),
        ),
        migrations.AddField(
            model_name='odoocredentials',
            name='shipping_fee_account_id',
            field=models.CharField(blank=True, default='', help_text='Odoo account ID for shipping fee journal entries', max_length=255),
        ),
        migrations.AddField(
            model_name='odoocredentials',
            name='tax_id',
            field=models.CharField(blank=True, default='', help_text='Odoo tax ID to apply on invoice lines', max_length=255),
        ),
        migrations.AddField(
            model_name='quickbookscredentials',
            name='shipping_fee_account_id',
            field=models.CharField(blank=True, default='', help_text='QuickBooks item/account ID for shipping fee line items', max_length=255),
        ),
        migrations.AddField(
            model_name='quickbookscredentials',
            name='tax_id',
            field=models.CharField(blank=True, default='', help_text='QuickBooks tax code/rate ID to apply on invoice lines', max_length=255),
        ),
        migrations.CreateModel(
            name='OrderSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('ODOO_SO', 'Odoo Sales Order'), ('ODOO_INVOICE', 'Odoo Invoice'), ('QUICKBOOKS', 'QuickBooks Invoice')], max_length=20)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=10)),
                ('external_id', models.CharField(blank=True, default='', help_text='ID returned by the external platform (e.g. Odoo SO ID, QB Invoice ID)', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='integrations.integration')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', '-created_at'], name='integration_order_i_b74ca7_idx'), models.Index(fields=['integration', '-created_at'], name='integration_integra_6feffc_idx'), models.Index(fields=['status', '-created_at'], name='integration_status_1aafe8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductMarketMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odoo_product_id', models.CharField(blank=True, default='', help_text='Odoo product template ID for this market', max_length=255)),
                ('quickbooks_product_id', models.CharField(blank=True, default='', help_text='QuickBooks item ID for this market', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_mappings', to='products.market')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_mappings', to='products.product')),
            ],
            options={
                'ordering': ['product', 'market'],
                'indexes': [models.Index(fields=['product', 'market'], name='integration_product_1d1e19_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'market'), name='unique_product_market_mapping')],
            },
        ),
    ]
