# Generated by GitHub Copilot on 2026-03-17
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_auto_...'),  # Update to last migration name
    ]

    operations = [
        migrations.AddField(
            model_name='quickbookscredentials',
            name='invoice_prefix',
            field=models.CharField(max_length=20, blank=True, default='', help_text='Prefix to prepend to invoice numbers, e.g. SHT for SHT1000.'),
        ),
    ]
