# Generated by Django 6.0.3 on 2026-03-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0010_quickbooks_invoice_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickbookscredentials',
            name='access_token',
            field=models.TextField(blank=True, default='', help_text='OAuth 2.0 access token (short-lived, ~1 hour)'),
        ),
        migrations.AddField(
            model_name='quickbookscredentials',
            name='redirect_uri',
            field=models.URLField(blank=True, default='', help_text='OAuth redirect URI used during authorization'),
        ),
        migrations.AddField(
            model_name='quickbookscredentials',
            name='refresh_token',
            field=models.TextField(blank=True, default='', help_text='OAuth 2.0 refresh token (long-lived, ~100 days)'),
        ),
        migrations.AddField(
            model_name='quickbookscredentials',
            name='token_expiry',
            field=models.DateTimeField(blank=True, help_text='When the current access token expires', null=True),
        ),
    ]
