# Generated by Django 6.0.3 on 2026-03-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0011_add_quickbooks_oauth_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickbookscredentials',
            name='oauth_state',
            field=models.CharField(blank=True, default='', help_text='Cryptographic nonce for OAuth CSRF protection', max_length=64),
        ),
        migrations.AlterField(
            model_name='quickbookscredentials',
            name='client_key',
            field=models.CharField(help_text='OAuth 2.0 Client Secret (named client_key for legacy compatibility)', max_length=512),
        ),
    ]
