# Generated by Django 6.0.3 on 2026-03-18 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0012_add_oauth_state_field'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productmarketmapping',
            name='integration_product_1d1e19_idx',
        ),
        migrations.RemoveConstraint(
            model_name='productmarketmapping',
            name='unique_product_market_mapping',
        ),
        migrations.DeleteModel(
            name='ProductMarketMapping',
        ),
    ]
