# Generated by Django 6.0.3 on 2026-03-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0013_remove_product_id_fields_and_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='odoocredentials',
            name='default_product_id',
            field=models.CharField(blank=True, default='', help_text='Odoo product.product ID to use when no SKU match is found', max_length=255),
        ),
        migrations.AddField(
            model_name='quickbookscredentials',
            name='default_product_id',
            field=models.CharField(blank=True, default='', help_text='QuickBooks Item ID to use when no SKU match is found', max_length=255),
        ),
    ]
