# Generated by Django 6.0.3 on 2026-03-19 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0014_add_default_product_id'),
        ('products', '0011_remove_product_id_fields_and_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductIntegrationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_sku', models.CharField(help_text='The SKU or ID used by the external system to identify the product', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_mappings', to='integrations.integration')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_mappings', to='products.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'integration'], name='integration_product_b64823_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'integration'), name='unique_product_integration_mapping')],
            },
        ),
    ]
