# Generated by Django 6.0.3 on 2026-03-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0015_productintegrationmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='odoocredentials',
            name='discount_product_id',
            field=models.CharField(blank=True, help_text='Odoo product.product ID to use for discount lines', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quickbookscredentials',
            name='discount_product_id',
            field=models.CharField(blank=True, help_text='QuickBooks Item ID to use for discount lines', max_length=255, null=True),
        ),
    ]
