# Generated by Django 6.0.3 on 2026-03-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0016_odoocredentials_discount_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersynclog',
            name='request_payload',
            field=models.JSONField(blank=True, help_text='The JSON payload (or XML-RPC dict) sent during the sync attempt.', null=True),
        ),
    ]
