# Generated by Django 6.0.3 on 2026-03-07 14:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0004_remove_legacy_integration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.TextField(blank=True, help_text='Reason for cancellation'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='USD', help_text='ISO Currency Code (e.g., NGN, KES, USD)', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_note',
            field=models.TextField(blank=True, help_text='Note from customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('RETURNED', 'Returned')], db_index=True, default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total discount applied', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_codes',
            field=models.CharField(blank=True, help_text='Discount codes applied', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Exchange rate to base currency', max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfillment_status',
            field=models.CharField(choices=[('UNFULFILLED', 'Unfulfilled'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled'), ('FULFILLED', 'Fulfilled'), ('RESTOCKED', 'Restocked')], db_index=True, default='UNFULFILLED', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='is_cash_on_delivery',
            field=models.BooleanField(default=False, help_text='True if payment method is COD'),
        ),
        migrations.AddField(
            model_name='order',
            name='market',
            field=models.CharField(db_index=True, default='KE', help_text='Market/Country (e.g., Nigeria, Kenya, Ghana)', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_gateway',
            field=models.CharField(blank=True, help_text='Payment gateway used (e.g., Stripe, PayPal)', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('PREPAID', 'Prepaid'), ('CREDIT_CARD', 'Credit Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('OTHER', 'Other')], default='PREPAID', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AUTHORIZED', 'Authorized'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('PARTIALLY_REFUNDED', 'Partially Refunded'), ('REFUNDED', 'Refunded'), ('VOIDED', 'Voided')], db_index=True, default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='requires_shipping',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_line1',
            field=models.CharField(default='Shipping Line', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(default='City', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_country',
            field=models.CharField(default='KE', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_country_code',
            field=models.CharField(blank=True, help_text='ISO 2-letter country code', max_length=2),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(blank=True, help_text='Shipping method/carrier', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Shipping/delivery fee', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='shopify_created_at',
            field=models.DateTimeField(blank=True, help_text='Order creation time in Shopify', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shopify_customer_id',
            field=models.CharField(blank=True, help_text='Shopify Customer ID', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='shopify_note',
            field=models.TextField(blank=True, help_text='Order note from Shopify'),
        ),
        migrations.AddField(
            model_name='order',
            name='shopify_order_id',
            field=models.CharField(db_index=True, default=0, help_text='Shopify Order ID', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shopify_order_number',
            field=models.CharField(db_index=True, default='SH000', help_text='Shopify Order Number', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shopify_raw_data',
            field=models.JSONField(blank=True, default=dict, help_text='Raw Shopify order data'),
        ),
        migrations.AddField(
            model_name='order',
            name='shopify_tags',
            field=models.TextField(blank=True, help_text='Comma-separated tags from Shopify'),
        ),
        migrations.AddField(
            model_name='order',
            name='shopify_updated_at',
            field=models.DateTimeField(blank=True, help_text='Last update time in Shopify', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Subtotal before tax and shipping', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax/VAT rate percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total tax/VAT amount', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Shipment tracking number', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_url',
            field=models.URLField(blank=True, help_text='Tracking URL', max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Payment transaction ID', max_length=255),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount applied to this item', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fulfillment_status',
            field=models.CharField(blank=True, default='UNFULFILLED', max_length=30),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_gift_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(default='Aloe', help_text='Product name at time of order', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='properties',
            field=models.JSONField(blank=True, default=dict, help_text='Custom properties/line item properties'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='requires_shipping',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shopify_product_id',
            field=models.CharField(blank=True, help_text='Shopify Product ID', max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shopify_variant_id',
            field=models.CharField(blank=True, help_text='Shopify Variant ID', max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sku',
            field=models.CharField(blank=True, help_text='Product SKU', max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax amount for this item', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax rate applied to this item', max_digits=5),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_name',
            field=models.CharField(blank=True, help_text='Variant name (e.g., Size: Large, Color: Red)', max_length=255),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vendor',
            field=models.CharField(blank=True, help_text='Product vendor/supplier', max_length=255),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Item weight in grams', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='weight_unit',
            field=models.CharField(blank=True, default='g', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Final total amount (subtotal + tax + shipping - discount)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse handling this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='products.warehouse'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='Total price for this line item (quantity × unit_price)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shopify_order_id'], name='orders_orde_shopify_3c5bc5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['market', '-created_at'], name='orders_orde_market_199886_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['fulfillment_status', '-created_at'], name='orders_orde_fulfill_92c29b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status', '-created_at'], name='orders_orde_payment_8bdf8b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['delivery_status', '-created_at'], name='orders_orde_deliver_ab2be0_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_email'], name='orders_orde_custome_ca0107_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_cash_on_delivery', 'status'], name='orders_orde_is_cash_915416_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['shopify_product_id'], name='orders_orde_shopify_a38c17_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['shopify_variant_id'], name='orders_orde_shopify_c2547c_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['sku'], name='orders_orde_sku_737ca0_idx'),
        ),
    ]
