# Generated by Django 6.0.3 on 2026-03-07 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_billing_address_line1_and_more'),
        ('products', '0004_remove_legacy_integration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_channel',
            field=models.CharField(choices=[('WEBSITE', 'Website'), ('WHATSAPP', 'Whatsapp'), ('POS', 'Point of Sale')], db_index=True, default='WEBSITE', help_text='Sales channel for this Shopify order', max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_channel', '-created_at'], name='orders_orde_order_c_b40706_idx'),
        ),
    ]
