# Generated by Django 6.0.3 on 2026-03-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_order_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_channel',
            field=models.CharField(choices=[('WEBSITE', 'Website'), ('WHATSAPP', 'Whatsapp'), ('POS', 'Hub POS')], db_index=True, default='WEBSITE', help_text='Sales channel for this Shopify order', max_length=20),
        ),
    ]
