# Generated by Django 6.0.3 on 2026-03-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_order_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_image_url',
            field=models.URLField(blank=True, help_text='Product image URL at time of order', max_length=500, null=True),
        ),
    ]
