# Generated by Django 6.0.3 on 2026-03-12 00:00

from django.db import migrations, models


def _build_market_code(name: str, MarketModel):
    base = ''.join(ch for ch in (name or 'UNK').upper() if ch.isalpha())[:3] or 'MKT'
    candidate = base
    index = 1
    while MarketModel.objects.filter(code=candidate).exists():
        suffix = str(index)
        candidate = f"{base[: max(1, 3 - len(suffix))]}{suffix}"
        index += 1
    return candidate


def forwards(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    Market = apps.get_model('products', 'Market')

    for order in Order.objects.all().iterator():
        market_name = (getattr(order, 'market', '') or '').strip()
        currency = (getattr(order, 'currency', '') or '').strip().upper() or 'USD'

        if market_name:
            market_obj = Market.objects.filter(name__iexact=market_name).first()
            if market_obj is None:
                market_obj = Market.objects.filter(code__iexact=market_name).first()
        else:
            market_obj = None

        if market_obj is None:
            resolved_name = market_name or 'Unknown'
            market_obj, _ = Market.objects.get_or_create(
                name=resolved_name,
                defaults={
                    'code': _build_market_code(resolved_name, Market),
                    'currency': currency,
                    'is_active': True,
                },
            )

        order.market_ref_id = market_obj.id
        order.save(update_fields=['market_ref'])


def backwards(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')

    for order in Order.objects.select_related('market').all().iterator():
        market_obj = getattr(order, 'market', None)
        if market_obj is None:
            order.market = ''
            order.currency = 'USD'
        else:
            order.market = market_obj.name
            order.currency = market_obj.currency or 'USD'
        order.save(update_fields=['market', 'currency'])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_kititem'),
        ('orders', '0005_orderitem_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='market_ref',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.PROTECT,
                related_name='+',
                to='products.market',
            ),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name='order',
            name='market_ref',
            field=models.ForeignKey(
                help_text='Market/Country for this order',
                on_delete=models.PROTECT,
                related_name='orders',
                to='products.market',
            ),
        ),
        migrations.RemoveField(
            model_name='order',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='market',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='market_ref',
            new_name='market',
        ),
    ]

