# Generated by Django 6.0.3 on 2026-03-12 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_market_fk'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF to_regclass('public.orders_orde_market_199886_idx') IS NOT NULL THEN
                            ALTER INDEX orders_orde_market_199886_idx RENAME TO orders_orde_market__51bbfd_idx;
                        ELSIF to_regclass('public.orders_orde_market__51bbfd_idx') IS NULL THEN
                            CREATE INDEX orders_orde_market__51bbfd_idx ON orders_order (market_id, created_at DESC);
                        END IF;
                    END
                    $$;
                    """,
                    reverse_sql="""
                    DO $$
                    BEGIN
                        IF to_regclass('public.orders_orde_market__51bbfd_idx') IS NOT NULL THEN
                            ALTER INDEX orders_orde_market__51bbfd_idx RENAME TO orders_orde_market_199886_idx;
                        ELSIF to_regclass('public.orders_orde_market_199886_idx') IS NULL THEN
                            CREATE INDEX orders_orde_market_199886_idx ON orders_order (market_id, created_at DESC);
                        END IF;
                    END
                    $$;
                    """,
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='order',
                    new_name='orders_orde_market__51bbfd_idx',
                    old_name='orders_orde_market_199886_idx',
                ),
            ],
        ),
    ]
