# Generated by Django 6.0.3 on 2026-03-12 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_market_fk'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    code=lambda apps, schema_editor: schema_editor.execute("""
                        DO $$
                        BEGIN
                            IF to_regclass('public.orders_orde_market_199886_idx') IS NOT NULL THEN
                                ALTER INDEX orders_orde_market_199886_idx RENAME TO orders_orde_market__51bbfd_idx;
                            ELSIF to_regclass('public.orders_orde_market__51bbfd_idx') IS NULL THEN
                                CREATE INDEX orders_orde_market__51bbfd_idx ON orders_order (market_id, created_at DESC);
                            END IF;
                        END
                        $$;
                    """) if schema_editor.connection.vendor == 'postgresql' else None,
                    reverse_code=lambda apps, schema_editor: schema_editor.execute("""
                        DO $$
                        BEGIN
                            IF to_regclass('public.orders_orde_market__51bbfd_idx') IS NOT NULL THEN
                                ALTER INDEX orders_orde_market__51bbfd_idx RENAME TO orders_orde_market_199886_idx;
                            ELSIF to_regclass('public.orders_orde_market_199886_idx') IS NULL THEN
                                CREATE INDEX orders_orde_market_199886_idx ON orders_order (market_id, created_at DESC);
                            END IF;
                        END
                        $$;
                    """) if schema_editor.connection.vendor == 'postgresql' else None,
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='order',
                    new_name='orders_orde_market__51bbfd_idx',
                    old_name='orders_orde_market_199886_idx',
                ),
            ],
        ),
    ]
