# Generated by Django 6.0.3 on 2026-03-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_orders_orde_market_199886_idx_orders_orde_market__51bbfd_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='odoo_sales_invoice_id',
            field=models.CharField(blank=True, default='', help_text='Odoo Account Move (Invoice) record ID', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='odoo_sales_order_id',
            field=models.CharField(blank=True, default='', help_text='Odoo Sales Order record ID', max_length=255),
        ),
    ]
