# Generated by Django 6.0.3 on 2026-03-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_add_quickbooks_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='odoo_sync_status',
            field=models.CharField(choices=[('NOT_SYNCED', 'Not Synced'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='NOT_SYNCED', help_text='Status of sync to Odoo', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='quickbooks_sync_status',
            field=models.CharField(choices=[('NOT_SYNCED', 'Not Synced'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='NOT_SYNCED', help_text='Status of sync to QuickBooks', max_length=20),
        ),
    ]
