# Generated by Django 6.0.3 on 2026-03-25 09:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_odoo_sync_status_order_quickbooks_sync_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discounted per-unit price (unit_price minus per-unit discount). Null if no discount.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='Total price for this line item (quantity × effective price)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Gross (list) price per unit from Shopify price_set.shop_money.amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
