# Generated by Django 6.0.3 on 2026-03-07 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_requests', '0001_initial'),
        ('products', '0004_remove_legacy_integration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='productrequest',
            name='product_req_assigne_a43367_idx',
        ),
        migrations.RemoveIndex(
            model_name='productrequest',
            name='product_req_type_286358_idx',
        ),
        migrations.AddField(
            model_name='productrequest',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_to_approve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productrequest',
            name='reason',
            field=models.TextField(default='1', help_text='Reason for this request'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='productrequest',
            index=models.Index(fields=['approver', 'status'], name='product_req_approve_6ec56b_idx'),
        ),
        migrations.AddField(
            model_name='productrequestitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_items', to='products.product'),
        ),
        migrations.AddField(
            model_name='productrequestitem',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product_requests.productrequest'),
        ),
        migrations.RemoveField(
            model_name='productrequest',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='productrequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productrequest',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='productrequest',
            name='related_product',
        ),
        migrations.RemoveField(
            model_name='productrequest',
            name='related_warehouse',
        ),
        migrations.RemoveField(
            model_name='productrequest',
            name='title',
        ),
        migrations.RemoveField(
            model_name='productrequest',
            name='type',
        ),
        migrations.AddIndex(
            model_name='productrequestitem',
            index=models.Index(fields=['request', 'product'], name='product_req_request_3391d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productrequestitem',
            unique_together={('request', 'product')},
        ),
    ]
