# Generated by Django 6.0.3 on 2026-03-10 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_requests', '0002_productrequestitem_and_more'),
        ('products', '0007_seed_initial_markets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productrequest',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_requests', to='products.warehouse'),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('READY_TO_COLLECT', 'Ready to Collect'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='productrequest',
            index=models.Index(fields=['warehouse', 'status'], name='product_req_warehou_0da17f_idx'),
        ),
    ]
