# Generated by Django 6.0.3 on 2026-03-10 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_requests', '0003_productrequest_ready_at_productrequest_warehouse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('REQUEST_CREATED', 'Request Created'), ('REQUEST_APPROVED', 'Request Approved'), ('REQUEST_REJECTED', 'Request Rejected'), ('REQUEST_READY_TO_COLLECT', 'Request Ready to Collect'), ('EMAIL_TO_APPROVER_SENT', 'Approver Email Sent'), ('EMAIL_TO_MANAGER_SENT', 'Manager Email Sent'), ('EMAIL_TO_REQUESTER_SENT', 'Requester Email Sent')], max_length=64)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_request_events', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='product_requests.productrequest')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['request', 'created_at'], name='product_req_request_23ba92_idx'), models.Index(fields=['event_type', 'created_at'], name='product_req_event_t_eede4b_idx')],
            },
        ),
    ]
