# Generated by Django 6.0.3 on 2026-03-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_requests', '0004_productrequestevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('READY_TO_COLLECT', 'Ready to Collect'), ('COLLECTED', 'Collected'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='productrequestevent',
            name='event_type',
            field=models.CharField(choices=[('REQUEST_CREATED', 'Request Created'), ('REQUEST_APPROVED', 'Request Approved'), ('REQUEST_REJECTED', 'Request Rejected'), ('REQUEST_READY_TO_COLLECT', 'Request Ready to Collect'), ('REQUEST_COLLECTED', 'Request Collected'), ('EMAIL_TO_APPROVER_SENT', 'Approver Email Sent'), ('EMAIL_TO_MANAGER_SENT', 'Manager Email Sent'), ('EMAIL_TO_REQUESTER_SENT', 'Requester Email Sent')], max_length=64),
        ),
    ]
