# Generated by Django 6.0.3 on 2026-03-04 11:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_kit',
            field=models.BooleanField(default=False, help_text='True if this product is a kit composed of other products.'),
        ),
        migrations.CreateModel(
            name='KitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='How many units of the component are in one unit of the kit.', validators=[django.core.validators.MinValueValidator(1)])),
                ('component', models.ForeignKey(help_text='The component product included in the kit.', on_delete=django.db.models.deletion.CASCADE, related_name='used_in_kits', to='products.product')),
                ('kit', models.ForeignKey(help_text='The kit (parent) product.', limit_choices_to={'is_kit': True}, on_delete=django.db.models.deletion.CASCADE, related_name='kit_items', to='products.product')),
            ],
            options={
                'ordering': ['kit', 'component'],
                'constraints': [models.UniqueConstraint(fields=('kit', 'component'), name='unique_component_per_kit')],
            },
        ),
    ]
