# Generated by Django 6.0.3 on 2026-03-04 12:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_kit_kititem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='How many units of the component are in one unit of the bundle.', validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['bundle', 'component'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='kititem',
            name='unique_component_per_kit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_kit',
        ),
        migrations.AddField(
            model_name='product',
            name='is_bundle',
            field=models.BooleanField(default=False, help_text='True if this product is a bundle composed of other products.'),
        ),
        migrations.AddField(
            model_name='productbundle',
            name='bundle',
            field=models.ForeignKey(help_text='The bundle (parent) product.', limit_choices_to={'is_bundle': True}, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='products.product'),
        ),
        migrations.AddField(
            model_name='productbundle',
            name='component',
            field=models.ForeignKey(help_text='The component product included in the bundle.', on_delete=django.db.models.deletion.CASCADE, related_name='used_in_bundles', to='products.product'),
        ),
        migrations.RemoveField(
            model_name='kititem',
            name='component',
        ),
        migrations.RemoveField(
            model_name='kititem',
            name='kit',
        ),
        migrations.AddConstraint(
            model_name='productbundle',
            constraint=models.UniqueConstraint(fields=('bundle', 'component'), name='unique_component_per_bundle'),
        ),
        migrations.DeleteModel(
            name='KitItem',
        ),
    ]
