# Generated by Django 6.0.3 on 2026-03-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_is_physical'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Market/Country name (e.g., Kenya, Nigeria, Ghana)', max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Market code (e.g., KE, NG, GH)', max_length=10, unique=True)),
                ('currency', models.CharField(default='USD', help_text='Default currency code (e.g., KES, NGN, GHS)', max_length=3)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this market is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='products_ma_name_a34260_idx'), models.Index(fields=['code'], name='products_ma_code_f5dd73_idx'), models.Index(fields=['is_active', 'name'], name='products_ma_is_acti_fe54ac_idx')],
            },
        ),
    ]
