# Generated by Django 6.0.3 on 2026-03-10 08:34

from django.db import migrations
from django.utils import timezone


def seed_markets(apps, schema_editor):
    """Seed initial markets based on existing integrations and orders"""
    Market = apps.get_model('products', 'Market')

    # Create Kenya market
    Market.objects.get_or_create(
        name='Kenya',
        defaults={
            'code': 'KE',
            'currency': 'KES',
            'is_active': True,
        }
    )

    # Create Nigeria market
    Market.objects.get_or_create(
        name='Nigeria',
        defaults={
            'code': 'NG',
            'currency': 'NGN',
            'is_active': True,
        }
    )


def reverse_seed(apps, schema_editor):
    """Remove seeded markets"""
    Market = apps.get_model('products', 'Market')
    Market.objects.filter(code__in=['KE', 'NG']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_market'),
    ]

    operations = [
        migrations.RunPython(seed_markets, reverse_seed),
    ]

