# Generated by Django 6.0.3 on 2026-03-10 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_seed_initial_markets'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'db_table': 'products_productbundle',
                'ordering': ['kit', 'component'],
                'managed': False,
            },
        ),
    ]
