# Generated by Django 6.0.3 on 2026-03-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_kititem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='odoo_product_id',
            field=models.CharField(blank=True, default='', help_text='Odoo product template ID for sync', max_length=255),
        ),
    ]
