# Generated by Django 6.0.3 on 2026-03-18 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_add_quickbooks_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='odoo_product_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quickbooks_product_id',
        ),
    ]
